//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terminplan {
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinGanttViewStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinGanttViewStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Terminplan.WinGanttViewStrings", typeof(WinGanttViewStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unterpunkt für &apos;{0}&apos; hinzufügen ähnelt.
        /// </summary>
        internal static string GanttViewContextMenuItem_AddSubTask_Text {
            get {
                return ResourceManager.GetString("GanttViewContextMenuItem_AddSubTask_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unterbegriffe ausblenden ähnelt.
        /// </summary>
        internal static string GanttViewContextMenuItem_CollapseTask_Text {
            get {
                return ResourceManager.GetString("GanttViewContextMenuItem_CollapseTask_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorgang deaktivieren ähnelt.
        /// </summary>
        internal static string GanttViewContextMenuItem_DisableTask_Text {
            get {
                return ResourceManager.GetString("GanttViewContextMenuItem_DisableTask_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorgang aktivieren ähnelt.
        /// </summary>
        internal static string GanttViewContextMenuItem_EnableTask_Text {
            get {
                return ResourceManager.GetString("GanttViewContextMenuItem_EnableTask_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unterpunkte anzeigen ähnelt.
        /// </summary>
        internal static string GanttViewContextMenuItem_ExpandTask_Text {
            get {
                return ResourceManager.GetString("GanttViewContextMenuItem_ExpandTask_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorgang nach links verschieben ähnelt.
        /// </summary>
        internal static string GanttViewContextMenuItem_IndentTask_Text {
            get {
                return ResourceManager.GetString("GanttViewContextMenuItem_IndentTask_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorgang einfügen ähnelt.
        /// </summary>
        internal static string GanttViewContextMenuItem_InsertTask_Text {
            get {
                return ResourceManager.GetString("GanttViewContextMenuItem_InsertTask_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorgang nach rechts verschieben ähnelt.
        /// </summary>
        internal static string GanttViewContextMenuItem_OutdentTask_Text {
            get {
                return ResourceManager.GetString("GanttViewContextMenuItem_OutdentTask_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorgang löschen ähnelt.
        /// </summary>
        internal static string GanttViewContextMenuItem_RemoveTask_Text {
            get {
                return ResourceManager.GetString("GanttViewContextMenuItem_RemoveTask_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Informationen über den Vorgang ähnelt.
        /// </summary>
        internal static string GanttViewContextMenuItem_ShowDialog_Text {
            get {
                return ResourceManager.GetString("GanttViewContextMenuItem_ShowDialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Wert &quot;{0}&quot; ist ungültig für &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string Grid_Error_MessageBoxText_Generic {
            get {
                return ResourceManager.GetString("Grid_Error_MessageBoxText_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        /// </summary>
        internal static string Grid_Error_MessageBoxTitle_Generic {
            get {
                return ResourceManager.GetString("Grid_Error_MessageBoxTitle_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Vorgang ähnelt.
        /// </summary>
        internal static string Grid_Error_MessageBoxTitle_TaskException {
            get {
                return ResourceManager.GetString("Grid_Error_MessageBoxTitle_TaskException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verhalten ähnelt.
        /// </summary>
        internal static string LC_Behavior {
            get {
                return ResourceManager.GetString("LC_Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datum/Zeit-Intervall ähnelt.
        /// </summary>
        internal static string LC_DateTimeInterval {
            get {
                return ResourceManager.GetString("LC_DateTimeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sonstiges ähnelt.
        /// </summary>
        internal static string LC_Misc {
            get {
                return ResourceManager.GetString("LC_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Interaktion mit dem Benutzer ähnelt.
        /// </summary>
        internal static string LC_UserInteraction {
            get {
                return ResourceManager.GetString("LC_UserInteraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt eine Auflistung von von DateTimeInterval abgeleiteten Instanzen zurück, die die Datums- / Zeitintervalle definieren, die oberhalb des primären Intervalls erscheinen. ähnelt.
        /// </summary>
        internal static string LD_Timeline_AdditionalIntervals {
            get {
                return ResourceManager.GetString("LD_Timeline_AdditionalIntervals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt einen booleschen Wert zurück oder legt diesen fest, ob ein wöchentliches Datum-/ZeitIntervall automatisch oberhalb des primären Intervalls angezeigt wird. ähnelt.
        /// </summary>
        internal static string LD_Timeline_AutoAddAdditionalInterval {
            get {
                return ResourceManager.GetString("LD_Timeline_AutoAddAdditionalInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holt oder setzt  einen Wertk, der angibt, ob der Wert der ColumnWidth-Eigenschaft auf die ideale Breite für das primäre Intervall festgelegt ist, wenn der Benutzer den einstellbaren Bereich des Headers doppelt anklickt. ähnelt.
        /// </summary>
        internal static string LD_Timeline_ColumnAutoSizing {
            get {
                return ResourceManager.GetString("LD_Timeline_ColumnAutoSizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt das Aussehen der Header zurück, die das primäre Intervall und die Mitglieder der AdditionalIntervals-Auflistung repräsentieren. ähnelt.
        /// </summary>
        internal static string LD_Timeline_ColumnHeaderAppearance {
            get {
                return ResourceManager.GetString("LD_Timeline_ColumnHeaderAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holt oder setzt einen Wert, der angibt, ob der Benutzer den Wert der ColumnWidth-Eigenschaft ändern kann, indem er die rechte Kante eines primären Intervall-Spaltenkopfes zieht. ähnelt.
        /// </summary>
        internal static string LD_Timeline_ColumnSizing {
            get {
                return ResourceManager.GetString("LD_Timeline_ColumnSizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt die Breite in Pixeln des ColumnHeaderUIElements für das primäre Intervall und des TimeSlotUIElements zurück oder legt diese fest. ähnelt.
        /// </summary>
        internal static string LD_Timeline_ColumnWidth {
            get {
                return ResourceManager.GetString("LD_Timeline_ColumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt die Farbe der Zeilen und Pfeile, die eine Abhängigkeit von Vorgängen auf der Zeitleiste angeben, zurück oder legt diese fest. ähnelt.
        /// </summary>
        internal static string LD_Timeline_DependencyLinkColor {
            get {
                return ResourceManager.GetString("LD_Timeline_DependencyLinkColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt einen booleschen Wert zurück oder legt diesen fest, ob Zeilen gezeichnet werden, um eine Abhängigkeit von Vorgängen auf der Zeitleiste darzustellen. ähnelt.
        /// </summary>
        internal static string LD_Timeline_DrawDependencyLines {
            get {
                return ResourceManager.GetString("LD_Timeline_DrawDependencyLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt eine HorizontalScrollSettings-Instanz zurück, welche die kleinen und großen Inkremente für die horizontale Bildlaufleiste definiert. ähnelt.
        /// </summary>
        internal static string LD_Timeline_HorizontalScrollSettings {
            get {
                return ResourceManager.GetString("LD_Timeline_HorizontalScrollSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt den Minimalwert zurück, auf den die ColumnWidth-Eigenschaft während einer Größenänderung geändert werden kann. ähnelt.
        /// </summary>
        internal static string LD_Timeline_MinimumColumnResizeWidth {
            get {
                return ResourceManager.GetString("LD_Timeline_MinimumColumnResizeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt die Darstellung für Zeitfenster-UI-Elemente zurück, die im nicht arbeitsfreien Stundenbereich erscheinen. ähnelt.
        /// </summary>
        internal static string LD_Timeline_NonWorkingHourAppearance {
            get {
                return ResourceManager.GetString("LD_Timeline_NonWorkingHourAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt die vom DateTimeInterval abgeleitete Instanz zurück, die in der unteren Zeile der Spaltenüberschriften dargestellt ist und die das kleinste Zeitintervall für das Steuerelement definiert. ähnelt.
        /// </summary>
        internal static string LD_Timeline_PrimaryInterval {
            get {
                return ResourceManager.GetString("LD_Timeline_PrimaryInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt die ToolTipSettings-Instanz zurück, welche die Informationen festlegt, die dem Benutzer angezeigt werden, wenn ein Tooltip für einen Vorgang angezeigt wird. ähnelt.
        /// </summary>
        internal static string LD_Timeline_ToolTipSettings {
            get {
                return ResourceManager.GetString("LD_Timeline_ToolTipSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt die ToolTipSettingsDeadline-Instanz zurück,welche die Informationen festlegt, die dem Benutzer angezeigt werden, wenn eine QuickInfo für den Deadline-Indikator einer Aufgabe angezeigt wird. ähnelt.
        /// </summary>
        internal static string LD_Timeline_ToolTipSettingsDeadline {
            get {
                return ResourceManager.GetString("LD_Timeline_ToolTipSettingsDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt die ToolTipSettingsMilestone-Instanz zurück, wwelche die Informationen festlegt, die dem Benutzer angezeigt werden, wenn ein Tooltip für einen Meilenstein angezeigt wird. ähnelt.
        /// </summary>
        internal static string LD_Timeline_ToolTipSettingsMilestone {
            get {
                return ResourceManager.GetString("LD_Timeline_ToolTipSettingsMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt die ToolTipSettingsPercentComplete-Instanz zurück, welche die Informationen festlegt, die dem Benutzer angezeigt werden, wenn eine QuickInfo für den Prozent Fertiggestellt-Indikator eines Vorgangs angezeigt wird. ähnelt.
        /// </summary>
        internal static string LD_Timeline_ToolTipSettingsPercentComplete {
            get {
                return ResourceManager.GetString("LD_Timeline_ToolTipSettingsPercentComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt die ToolTipSettingsSummary-Instanz zurück, welche die Informationen festlegt, die dem Benutzer angezeigt werden, wenn eine Task-Tooltip für eine Zusammenfassung der Vorgänge angezeigt wird. ähnelt.
        /// </summary>
        internal static string LD_Timeline_ToolTipSettingsSummary {
            get {
                return ResourceManager.GetString("LD_Timeline_ToolTipSettingsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt die ToolTipSettingsTaskDependency-Instanz zurück, welche die Informationen festlegt, die dem Benutzer angezeigt werden, wenn einen Tooltip für eine Abhängigkeit von Vorgängen angezeigt wird. ähnelt.
        /// </summary>
        internal static string LD_Timeline_ToolTipSettingsTaskDependency {
            get {
                return ResourceManager.GetString("LD_Timeline_ToolTipSettingsTaskDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt das Aussehen für Zeitfenster-UI-Elemente zurück, die im Arbeitszeitbereich angezeigt werden. ähnelt.
        /// </summary>
        internal static string LD_Timeline_WorkingHourAppearance {
            get {
                return ResourceManager.GetString("LD_Timeline_WorkingHourAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt das Appearance-Objekt zurück, welches die visuelle Formatierung für die vom Steuerelement angezeigten Tooltips steuert ,oder legt diesen fes. ähnelt.
        /// </summary>
        internal static string LD_ToolTipSettings_Appearance {
            get {
                return ResourceManager.GetString("LD_ToolTipSettings_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt das Format zurück, das auf die in der Tooltip angezeigten Datums- / Zeitangaben angewendet wird, oder legt diesen fest. ähnelt.
        /// </summary>
        internal static string LD_ToolTipSettings_DateTimeFormat {
            get {
                return ResourceManager.GetString("LD_ToolTipSettings_DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt einen Wert zurück, welcher angibt, ob der Wert Fertiggestellt von des Vorgangs im Tooltip angezeigt werden soll, oder legt diesen fest. ähnelt.
        /// </summary>
        internal static string LD_ToolTipSettings_DisplayCompleteThrough {
            get {
                return ResourceManager.GetString("LD_ToolTipSettings_DisplayCompleteThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt einen Wert zurück, welcher angibt, ob der Wert der Deadline des Vorgangs imTooltip angezeigt werden soll, oder legt diesen fest. ähnelt.
        /// </summary>
        internal static string LD_ToolTipSettings_DisplayDeadline {
            get {
                return ResourceManager.GetString("LD_ToolTipSettings_DisplayDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt einen Wert zurück, welcher angibt, ob die Dauer des Vorgangs in der Tooltip angezeigt werden solll, oder legt diesen fest. ähnelt.
        /// </summary>
        internal static string LD_ToolTipSettings_DisplayDuration {
            get {
                return ResourceManager.GetString("LD_ToolTipSettings_DisplayDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt einen Wert zurück, der angibt, ob der Wert des Ende-Datums der Aufgabe im Tooltip angezeigt werden soll, oder legt diesen fest. ähnelt.
        /// </summary>
        internal static string LD_ToolTipSettings_DisplayEndDateTime {
            get {
                return ResourceManager.GetString("LD_ToolTipSettings_DisplayEndDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt einen Wert zurück, der angibt, ob der Name des Vorgangs in der Tooltip angezeigt werden soll, oder legt diesen fest. ähnelt.
        /// </summary>
        internal static string LD_ToolTipSettings_DisplayName {
            get {
                return ResourceManager.GetString("LD_ToolTipSettings_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt einen Wert zurück,welcherr angibt, ob der Wert Prozent fertigestellt des Vorgangs im Tooltip angezeigt werden soll, oder legt diesen fest. ähnelt.
        /// </summary>
        internal static string LD_ToolTipSettings_DisplayPercentComplete {
            get {
                return ResourceManager.GetString("LD_ToolTipSettings_DisplayPercentComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt einen Wert zurück, der angibt, ob der Wert der StartDateTime-Eigenschaft des Vorgangs im Tooltip angezeigt werden solll, oder legt diesen fest. ähnelt.
        /// </summary>
        internal static string LD_ToolTipSettings_DisplayStartDateTime {
            get {
                return ResourceManager.GetString("LD_ToolTipSettings_DisplayStartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holt oder setzt einen Wert, welcher angibt, ob ein Titel im Tooltip angezeigt werden soll. ähnelt.
        /// </summary>
        internal static string LD_ToolTipSettings_DisplayTitle {
            get {
                return ResourceManager.GetString("LD_ToolTipSettings_DisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holt oder setzt einen Wert zurück, welcher angibt, ob ein Tooltip angezeigt wird. ähnelt.
        /// </summary>
        internal static string LD_ToolTipSettings_DisplayToolTip {
            get {
                return ResourceManager.GetString("LD_ToolTipSettings_DisplayToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holt oder setzt die Zeichenfolge, welche als Titel im Tooltip angezeigt wird. ähnelt.
        /// </summary>
        internal static string LD_ToolTipSettings_Title {
            get {
                return ResourceManager.GetString("LD_ToolTipSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holt oder setzt das Appearance-Objekt, welches die visuelle Formatierung für die Vorgangs-Abhängigkeit angezeigten Tooltips steuert. ähnelt.
        /// </summary>
        internal static string LD_ToolTipSettingsTaskDependency_Appearance {
            get {
                return ResourceManager.GetString("LD_ToolTipSettingsTaskDependency_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holt oder setzt einen Wert, welcher angibt, ob der Name des abhängigen Vorgangs im Tooltip angezeigt werden soll. ähnelt.
        /// </summary>
        internal static string LD_ToolTipSettingsTaskDependency_DisplayDependent {
            get {
                return ResourceManager.GetString("LD_ToolTipSettingsTaskDependency_DisplayDependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holt oder setzt einen Wert, welcher angibt, ob der Name des Vorgänger-Vorgangs im Tooltip angezeigt werden soll. ähnelt.
        /// </summary>
        internal static string LD_ToolTipSettingsTaskDependency_DisplayPredecessor {
            get {
                return ResourceManager.GetString("LD_ToolTipSettingsTaskDependency_DisplayPredecessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holt oder setzt einen Wertk, welcher angibt, ob der Wert für die Art der Abhängigkeit im Tooltip angezeigt werden soll. ähnelt.
        /// </summary>
        internal static string LD_ToolTipSettingsTaskDependency_DisplayTaskDependencyType {
            get {
                return ResourceManager.GetString("LD_ToolTipSettingsTaskDependency_DisplayTaskDependencyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holt oder setzt das primäre Aussehen für das Steuerelement. ähnelt.
        /// </summary>
        internal static string LD_UltraGanttView_Appearance {
            get {
                return ResourceManager.GetString("LD_UltraGanttView_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holt oder setzt einen Wert, der angibt, ob das Standardkontextmenü automatisch angezeigt wird, wenn der Benutzer mit der rechten Maustaste in den entsprechenden Bereich des Steuerelements klickt. ähnelt.
        /// </summary>
        internal static string LD_UltraGanttView_AutoDisplayDefaultContextMenu {
            get {
                return ResourceManager.GetString("LD_UltraGanttView_AutoDisplayDefaultContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt einen Wert zurück, der angibt, ob der Vorgangs-Dialog automatisch angezeigt wird, wenn der Benutzer im entsprechenden Bereich des Steuerelements doppelklickt. ähnelt.
        /// </summary>
        internal static string LD_UltraGanttView_AutoDisplayTaskDialog {
            get {
                return ResourceManager.GetString("LD_UltraGanttView_AutoDisplayTaskDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holt oder setzt einen Wert, welcher die Breite des Diagrammbereichs des Steuerelements bestimmt. ähnelt.
        /// </summary>
        internal static string LD_UltraGanttView_ChartAreaWidth {
            get {
                return ResourceManager.GetString("LD_UltraGanttView_ChartAreaWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wird ausgelöst, bevor das benutzerdefinierte ContextMenu des Steuerelements angezeigt wird. ähnelt.
        /// </summary>
        internal static string LD_UltraGanttView_ContextMenuInitializing {
            get {
                return ResourceManager.GetString("LD_UltraGanttView_ContextMenuInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holt oder setzt einen Wert, welcher die Breite des Rasterbereichs des Steuerelements bestimmt. ähnelt.
        /// </summary>
        internal static string LD_UltraGanttView_GridAreaWidth {
            get {
                return ResourceManager.GetString("LD_UltraGanttView_GridAreaWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holt oder setzt einen Wert, welcher die gitterspezifischen Eigenschaften der Task bestimmt, beispielsweise das Aussehen der Zeile und die Einstellungen für die Zellen. ähnelt.
        /// </summary>
        internal static string LD_UltraGanttView_GridSettings {
            get {
                return ResourceManager.GetString("LD_UltraGanttView_GridSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt die Art und Weise zurück, in der das Steuerelement auf Änderungen in seiner Breite reagiert oder legt diese fest. ähnelt.
        /// </summary>
        internal static string LD_UltraGanttView_HorizontalResizeMode {
            get {
                return ResourceManager.GetString("LD_UltraGanttView_HorizontalResizeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wird ausgelöst, wenn der Benutzer das Resources-Feld im Vorgänge-Grid mit einem oder mehreren ungültigen Werten verlässt. ähnelt.
        /// </summary>
        internal static string LD_UltraGanttView_ResourceParseError {
            get {
                return ResourceManager.GetString("LD_UltraGanttView_ResourceParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wird ausgelöst, bevor der Vorgangs-Dialog angezeigt wird. ähnelt.
        /// </summary>
        internal static string LD_UltraGanttView_TaskDialogDisplaying {
            get {
                return ResourceManager.GetString("LD_UltraGanttView_TaskDialogDisplaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wird ausgelöst, wenn ein Ziehvorgang für ein Task-Element erfolgreich abgeschlossen wurde. ähnelt.
        /// </summary>
        internal static string LD_UltraGanttView_TaskElementDragComplete {
            get {
                return ResourceManager.GetString("LD_UltraGanttView_TaskElementDragComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wird während eines Zieh-Vorgangs für einVorgangs-Element ausgelöst. ähnelt.
        /// </summary>
        internal static string LD_UltraGanttView_TaskElementDragging {
            get {
                return ResourceManager.GetString("LD_UltraGanttView_TaskElementDragging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt eine TaskSettings-Instanz zurück, welche festlegt, ob der Benutzer Vorgänge bearbeiten oder löschen kann. ähnelt.
        /// </summary>
        internal static string LD_UltraGanttView_TaskSettings {
            get {
                return ResourceManager.GetString("LD_UltraGanttView_TaskSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wird ausgelöst, bevor ein Tooltip für ein Vorgangs-Element angezeigt wird. ähnelt.
        /// </summary>
        internal static string LD_UltraGanttView_TaskToolTipDisplaying {
            get {
                return ResourceManager.GetString("LD_UltraGanttView_TaskToolTipDisplaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wird sofort ausgelöst, bevor die untergeordneten Elemente für ein ColumnHeaderUIElement initialisiert werden, was den Benutzern die Möglichkeit gibt, den Text und / oder das Bild, das angezeigt wird, zu ändern. ähnelt.
        /// </summary>
        internal static string LD_UltraGanttView_Timeline_ColumnHeaderInitializing {
            get {
                return ResourceManager.GetString("LD_UltraGanttView_Timeline_ColumnHeaderInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wird ausgelöst, bevor ein Tooltip für ein ColumnHeaderUIElement angezeigt wird. ähnelt.
        /// </summary>
        internal static string LD_UltraGanttView_TimelineColumnHeaderToolTipDisplaying {
            get {
                return ResourceManager.GetString("LD_UltraGanttView_TimelineColumnHeaderToolTipDisplaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wird ausgelöst, wenn ein DateNavigationButtonUIElement angeklickt wird, was dem Benutzer die Möglichkeit gibt, die getroffene Aktion zu ändern. ähnelt.
        /// </summary>
        internal static string LD_UltraGanttView_TimelineDateNavigationButtonClicked {
            get {
                return ResourceManager.GetString("LD_UltraGanttView_TimelineDateNavigationButtonClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wird ausgelöst, wenn das primäre Intervall geändert wurde. ähnelt.
        /// </summary>
        internal static string LD_UltraGanttView_TimelinePrimaryIntervalChanged {
            get {
                return ResourceManager.GetString("LD_UltraGanttView_TimelinePrimaryIntervalChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt ein Objekt zurück, welches Eigenschaften enthält, die eine Möglichkeit bieten, die zeitleistenbezogenen Ansichten des Steuerelements anzupassen. ähnelt.
        /// </summary>
        internal static string LD_UltraGanttView_TimelineSettings {
            get {
                return ResourceManager.GetString("LD_UltraGanttView_TimelineSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wird ausgelöst, nachdem der Datumsbereich, welcher von der VisibleDateTimeRange-Eigenschaft zurückgegeben wird, geändert wurde. ähnelt.
        /// </summary>
        internal static string LD_UltraGanttView_TimelineVisibleDateTimeRange {
            get {
                return ResourceManager.GetString("LD_UltraGanttView_TimelineVisibleDateTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt das Aussehen für das VerticalSplitterUIElement zurück, welches den Grid-bereich und den Diagrammbereich des Steuerelements trennt oder legt dieses fest. ähnelt.
        /// </summary>
        internal static string LD_UltraGanttView_VerticalSplitterAppearance {
            get {
                return ResourceManager.GetString("LD_UltraGanttView_VerticalSplitterAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wird ausgelöst, wenn ein Bewegen des VerticalSplitterUIElement vom Benutzer normal beendet wird. ähnelt.
        /// </summary>
        internal static string LD_UltraGanttView_VerticalSplitterDragged {
            get {
                return ResourceManager.GetString("LD_UltraGanttView_VerticalSplitterDragged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wird ausgelöst, wenn das VerticalSplitterUIElement vom Benutzer bewegt wird. ähnelt.
        /// </summary>
        internal static string LD_UltraGanttView_VerticalSplitterDragging {
            get {
                return ResourceManager.GetString("LD_UltraGanttView_VerticalSplitterDragging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gibt zurück t, ob der vertikale Splitter, welcher den Bereichs des Grids und Diagrammfläche in der Benutzeroberfläche trennt , aktiviert ist, oder legt dies fest. ähnelt.
        /// </summary>
        internal static string LD_UltraGanttView_VerticalSplitterEnabled {
            get {
                return ResourceManager.GetString("LD_UltraGanttView_VerticalSplitterEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holt oder setzt einen Wert, welcher  den Mindestwert festlegt, für den die Eigenschaften GridAreaWidth und ChartAreaWidth über eine Größenänderung mit dem vertikalen Teiler festgelegt werden können. ähnelt.
        /// </summary>
        internal static string LD_UltraGanttView_VerticalSplitterMinimumResizeWidth {
            get {
                return ResourceManager.GetString("LD_UltraGanttView_VerticalSplitterMinimumResizeWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Holt oder setzt einen Wert, welcher die Breite des VerticalSplitterUIElement bestimmt, welches die Grid- und Diagrammbereiche des Steuerelements trennt. ähnelt.
        /// </summary>
        internal static string LD_UltraGanttView_VerticalSplitterWidth {
            get {
                return ResourceManager.GetString("LD_UltraGanttView_VerticalSplitterWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neuer Unterpunkt ähnelt.
        /// </summary>
        internal static string NewSubTask_Text {
            get {
                return ResourceManager.GetString("NewSubTask_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neuer Vorgang ähnelt.
        /// </summary>
        internal static string NewTask_Text {
            get {
                return ResourceManager.GetString("NewTask_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine oder mehrere der angegebenen Ressourcen sind nicht vorhanden. {1}Sollen die folgenden Ressourcen hinzufügt werden: &quot;{0}&quot;? ähnelt.
        /// </summary>
        internal static string ResourceParseError_MessageBoxText {
            get {
                return ResourceManager.GetString("ResourceParseError_MessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Prozentsatz der Fertigstellung kann nicht auf einen Arbeitsinhalt festgelegt werden, da dieser durch den Prozentsatz der Fertigstellung seiner Aufgaben festgelegt ist. ähnelt.
        /// </summary>
        internal static string SummaryTaskException_CannotSetPercentComplete {
            get {
                return ResourceManager.GetString("SummaryTaskException_CannotSetPercentComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die unbenannt ähnelt.
        /// </summary>
        internal static string Task_Name_Unnamed {
            get {
                return ResourceManager.GetString("Task_Name_Unnamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erweitert ähnelt.
        /// </summary>
        internal static string TaskDialog_AdvancedTab {
            get {
                return ResourceManager.GetString("TaskDialog_AdvancedTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbruch ähnelt.
        /// </summary>
        internal static string TaskDialog_BtnCancel {
            get {
                return ResourceManager.GetString("TaskDialog_BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string TaskDialog_BtnOK {
            get {
                return ResourceManager.GetString("TaskDialog_BtnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CalendarInfo sollte niemals null zurückgeben. ähnelt.
        /// </summary>
        internal static string TaskDialog_CalendarInfoNullError {
            get {
                return ResourceManager.GetString("TaskDialog_CalendarInfoNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        /// </summary>
        internal static string TaskDialog_ErrorTitle {
            get {
                return ResourceManager.GetString("TaskDialog_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allgemein ähnelt.
        /// </summary>
        internal static string TaskDialog_GeneralTab {
            get {
                return ResourceManager.GetString("TaskDialog_GeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ungültiger Besitzer gefunden. Bitte einen gültigen Wert verwenden. ähnelt.
        /// </summary>
        internal static string TaskDialog_InvalidOwnerError {
            get {
                return ResourceManager.GetString("TaskDialog_InvalidOwnerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte einen gültigen Ressourcennamen eingeben ähnelt.
        /// </summary>
        internal static string TaskDialog_InvalidResourceNameError {
            get {
                return ResourceManager.GetString("TaskDialog_InvalidResourceNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte eine gültige Zeilennummer eingeben. ähnelt.
        /// </summary>
        internal static string TaskDialog_InvalidRowNumberError {
            get {
                return ResourceManager.GetString("TaskDialog_InvalidRowNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unbekannte Tabulatortaste in der FromTabDialogPage ähnelt.
        /// </summary>
        internal static string TaskDialog_InvalidTabKeyError {
            get {
                return ResourceManager.GetString("TaskDialog_InvalidTabKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie einen gültigen Wert für die Einschränkung des Vorgangs ein. ähnelt.
        /// </summary>
        internal static string TaskDialog_InvalidTaskContraint {
            get {
                return ResourceManager.GetString("TaskDialog_InvalidTaskContraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte einen gültigen Typ für die Abhängigkeit des Vorgangs eingeben. ähnelt.
        /// </summary>
        internal static string TaskDialog_InvalidTaskDependencyTypeError {
            get {
                return ResourceManager.GetString("TaskDialog_InvalidTaskDependencyTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte einen gültigen Vorgangsnamen eingeben. ähnelt.
        /// </summary>
        internal static string TaskDialog_InvalidTaskNameError {
            get {
                return ResourceManager.GetString("TaskDialog_InvalidTaskNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine ungültiges Paar aus Zeilennummer und Vorgangsnamen wurde gefunden. Bitte einen gültigen Vorgangsnamen und Zeilennummer verwenden. ähnelt.
        /// </summary>
        internal static string TaskDialog_InvalidTaskNameOrRowNumber {
            get {
                return ResourceManager.GetString("TaskDialog_InvalidTaskNameOrRowNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Termin der Einschränkung: ähnelt.
        /// </summary>
        internal static string TaskDialog_lblConstraintDate {
            get {
                return ResourceManager.GetString("TaskDialog_lblConstraintDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorgang einschränken ähnelt.
        /// </summary>
        internal static string TaskDialog_lblConstraintTask {
            get {
                return ResourceManager.GetString("TaskDialog_lblConstraintTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Art der Einschränkung: ähnelt.
        /// </summary>
        internal static string TaskDialog_lblConstraintType {
            get {
                return ResourceManager.GetString("TaskDialog_lblConstraintType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Termine ähnelt.
        /// </summary>
        internal static string TaskDialog_lblDates {
            get {
                return ResourceManager.GetString("TaskDialog_lblDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deadline: ähnelt.
        /// </summary>
        internal static string TaskDialog_lblDeadline {
            get {
                return ResourceManager.GetString("TaskDialog_lblDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dauer: ähnelt.
        /// </summary>
        internal static string TaskDialog_lblDuration {
            get {
                return ResourceManager.GetString("TaskDialog_lblDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ende: ähnelt.
        /// </summary>
        internal static string TaskDialog_lblEndDate {
            get {
                return ResourceManager.GetString("TaskDialog_lblEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorgang als Meilenstein markieren ähnelt.
        /// </summary>
        internal static string TaskDialog_lblMilestone {
            get {
                return ResourceManager.GetString("TaskDialog_lblMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        internal static string TasKDialog_lblName {
            get {
                return ResourceManager.GetString("TasKDialog_lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notizen: ähnelt.
        /// </summary>
        internal static string TaskDialog_lblNotes {
            get {
                return ResourceManager.GetString("TaskDialog_lblNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prozent fertiggestellt: ähnelt.
        /// </summary>
        internal static string TaskDialog_lblPrecentageComplete {
            get {
                return ResourceManager.GetString("TaskDialog_lblPrecentageComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorgänger: ähnelt.
        /// </summary>
        internal static string TaskDialog_lblPredecessors {
            get {
                return ResourceManager.GetString("TaskDialog_lblPredecessors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ressourcen: ähnelt.
        /// </summary>
        internal static string TaskDialog_lblResources {
            get {
                return ResourceManager.GetString("TaskDialog_lblResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start: ähnelt.
        /// </summary>
        internal static string TaskDialog_lblStartDate {
            get {
                return ResourceManager.GetString("TaskDialog_lblStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notitzen ähnelt.
        /// </summary>
        internal static string TaskDialog_NotesTab {
            get {
                return ResourceManager.GetString("TaskDialog_NotesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Besitzerr darf nicht null sein. ähnelt.
        /// </summary>
        internal static string TaskDialog_NullOwnerError {
            get {
                return ResourceManager.GetString("TaskDialog_NullOwnerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die t ähnelt.
        /// </summary>
        internal static string TaskDialog_NumericEditorDurationMaskDays {
            get {
                return ResourceManager.GetString("TaskDialog_NumericEditorDurationMaskDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorgänger ähnelt.
        /// </summary>
        internal static string TaskDialog_PredecessorsTab {
            get {
                return ResourceManager.GetString("TaskDialog_PredecessorsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Projekt sollte niemals null zurückgeben. ähnelt.
        /// </summary>
        internal static string TaskDialog_ProjectNullError {
            get {
                return ResourceManager.GetString("TaskDialog_ProjectNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ressourcenname ähnelt.
        /// </summary>
        internal static string TaskDialog_ResourceNameCaption {
            get {
                return ResourceManager.GetString("TaskDialog_ResourceNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ressourcen ähnelt.
        /// </summary>
        internal static string TaskDialog_ResourcesTab {
            get {
                return ResourceManager.GetString("TaskDialog_ResourcesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeilennummer ähnelt.
        /// </summary>
        internal static string TaskDialog_RowNumberCaption {
            get {
                return ResourceManager.GetString("TaskDialog_RowNumberCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Vorgangs-Dialog unterstützt keine nicht-modale Anzeige. Verwenden Sie die ShowDialog-Methode, um den Dialog zu starten. ähnelt.
        /// </summary>
        internal static string TaskDialog_ShowNotSupported {
            get {
                return ResourceManager.GetString("TaskDialog_ShowNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Typ für die Abhängigkeit des Vorgangs ähnelt.
        /// </summary>
        internal static string TaskDialog_TaskDependencyTypeCaption {
            get {
                return ResourceManager.GetString("TaskDialog_TaskDependencyTypeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name des Vorgangs ähnelt.
        /// </summary>
        internal static string TaskDialog_TaskNameCaption {
            get {
                return ResourceManager.GetString("TaskDialog_TaskNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Informationen zum Vorgang ähnelt.
        /// </summary>
        internal static string TaskDialog_Title {
            get {
                return ResourceManager.GetString("TaskDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update fehlgeschlagen ähnelt.
        /// </summary>
        internal static string TaskDialog_UpdateFailedTitle {
            get {
                return ResourceManager.GetString("TaskDialog_UpdateFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Art der Einschränkung ähnelt.
        /// </summary>
        internal static string TaskProxy_PropertyDisplayName_Task_Constraint {
            get {
                return ResourceManager.GetString("TaskProxy_PropertyDisplayName_Task.Constraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datum der Einschränkung ähnelt.
        /// </summary>
        internal static string TaskProxy_PropertyDisplayName_Task_ConstraintDateTime {
            get {
                return ResourceManager.GetString("TaskProxy_PropertyDisplayName_Task.ConstraintDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deadline ähnelt.
        /// </summary>
        internal static string TaskProxy_PropertyDisplayName_Task_Deadline {
            get {
                return ResourceManager.GetString("TaskProxy_PropertyDisplayName_Task.Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorgänger ähnelt.
        /// </summary>
        internal static string TaskProxy_PropertyDisplayName_Task_Dependencies {
            get {
                return ResourceManager.GetString("TaskProxy_PropertyDisplayName_Task.Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dauer ähnelt.
        /// </summary>
        internal static string TaskProxy_PropertyDisplayName_Task_Duration {
            get {
                return ResourceManager.GetString("TaskProxy_PropertyDisplayName_Task.Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ende ähnelt.
        /// </summary>
        internal static string TaskProxy_PropertyDisplayName_Task_EndDateTime {
            get {
                return ResourceManager.GetString("TaskProxy_PropertyDisplayName_Task.EndDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Meilenstein ähnelt.
        /// </summary>
        internal static string TaskProxy_PropertyDisplayName_Task_Milestone {
            get {
                return ResourceManager.GetString("TaskProxy_PropertyDisplayName_Task.Milestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorgang ähnelt.
        /// </summary>
        internal static string TaskProxy_PropertyDisplayName_Task_Name {
            get {
                return ResourceManager.GetString("TaskProxy_PropertyDisplayName_Task.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notitzen ähnelt.
        /// </summary>
        internal static string TaskProxy_PropertyDisplayName_Task_Notes {
            get {
                return ResourceManager.GetString("TaskProxy_PropertyDisplayName_Task.Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % Fertiggestellt ähnelt.
        /// </summary>
        internal static string TaskProxy_PropertyDisplayName_Task_PercentComplete {
            get {
                return ResourceManager.GetString("TaskProxy_PropertyDisplayName_Task.PercentComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ressourcennamen ähnelt.
        /// </summary>
        internal static string TaskProxy_PropertyDisplayName_Task_Resources {
            get {
                return ResourceManager.GetString("TaskProxy_PropertyDisplayName_Task.Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        internal static string TaskProxy_PropertyDisplayName_Task_StartDateTime {
            get {
                return ResourceManager.GetString("TaskProxy_PropertyDisplayName_Task.StartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tage ähnelt.
        /// </summary>
        internal static string TimeSpanEditor_DayDisplayString_Plural {
            get {
                return ResourceManager.GetString("TimeSpanEditor_DayDisplayString_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tag ähnelt.
        /// </summary>
        internal static string TimeSpanEditor_DayDisplayString_Singular {
            get {
                return ResourceManager.GetString("TimeSpanEditor_DayDisplayString_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die h ähnelt.
        /// </summary>
        internal static string TimeSpanEditor_HourDisplayString_Plural {
            get {
                return ResourceManager.GetString("TimeSpanEditor_HourDisplayString_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die h ähnelt.
        /// </summary>
        internal static string TimeSpanEditor_HourDisplayString_Singular {
            get {
                return ResourceManager.GetString("TimeSpanEditor_HourDisplayString_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die min ähnelt.
        /// </summary>
        internal static string TimeSpanEditor_MinuteDisplayString_Plural {
            get {
                return ResourceManager.GetString("TimeSpanEditor_MinuteDisplayString_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die min ähnelt.
        /// </summary>
        internal static string TimeSpanEditor_MinuteDisplayString_Singular {
            get {
                return ResourceManager.GetString("TimeSpanEditor_MinuteDisplayString_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wo ähnelt.
        /// </summary>
        internal static string TimeSpanEditor_WeekDisplayString_Plural {
            get {
                return ResourceManager.GetString("TimeSpanEditor_WeekDisplayString_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wo ähnelt.
        /// </summary>
        internal static string TimeSpanEditor_WeekDisplayString_Singular {
            get {
                return ResourceManager.GetString("TimeSpanEditor_WeekDisplayString_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorgang ähnelt.
        /// </summary>
        internal static string ToolTipSettings_DefaultTitle {
            get {
                return ResourceManager.GetString("ToolTipSettings_DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deadline ähnelt.
        /// </summary>
        internal static string ToolTipSettings_DefaultTitle_Deadline {
            get {
                return ResourceManager.GetString("ToolTipSettings_DefaultTitle_Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Meilenstein ähnelt.
        /// </summary>
        internal static string ToolTipSettings_DefaultTitle_Milestone {
            get {
                return ResourceManager.GetString("ToolTipSettings_DefaultTitle_Milestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fortschritt ähnelt.
        /// </summary>
        internal static string ToolTipSettings_DefaultTitle_PercentComplete {
            get {
                return ResourceManager.GetString("ToolTipSettings_DefaultTitle_PercentComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zusammenfassung ähnelt.
        /// </summary>
        internal static string ToolTipSettings_DefaultTitle_Summary {
            get {
                return ResourceManager.GetString("ToolTipSettings_DefaultTitle_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Durchgehen ähnelt.
        /// </summary>
        internal static string ToolTipSettings_Prefix_CompleteThrough {
            get {
                return ResourceManager.GetString("ToolTipSettings_Prefix_CompleteThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deadline ähnelt.
        /// </summary>
        internal static string ToolTipSettings_Prefix_Deadline {
            get {
                return ResourceManager.GetString("ToolTipSettings_Prefix_Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dauer ähnelt.
        /// </summary>
        internal static string ToolTipSettings_Prefix_Duration {
            get {
                return ResourceManager.GetString("ToolTipSettings_Prefix_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ende ähnelt.
        /// </summary>
        internal static string ToolTipSettings_Prefix_Finish {
            get {
                return ResourceManager.GetString("ToolTipSettings_Prefix_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorgang ähnelt.
        /// </summary>
        internal static string ToolTipSettings_Prefix_Name {
            get {
                return ResourceManager.GetString("ToolTipSettings_Prefix_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die % fertiggestellt ähnelt.
        /// </summary>
        internal static string ToolTipSettings_Prefix_PercentComplete {
            get {
                return ResourceManager.GetString("ToolTipSettings_Prefix_PercentComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        internal static string ToolTipSettings_Prefix_Start {
            get {
                return ResourceManager.GetString("ToolTipSettings_Prefix_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nach ähnelt.
        /// </summary>
        internal static string ToolTipSettingsTaskDependency_Prefix_Dependent {
            get {
                return ResourceManager.GetString("ToolTipSettingsTaskDependency_Prefix_Dependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Von ähnelt.
        /// </summary>
        internal static string ToolTipSettingsTaskDependency_Prefix_Predecessor {
            get {
                return ResourceManager.GetString("ToolTipSettingsTaskDependency_Prefix_Predecessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verknüpfung zum Vorgang ähnelt.
        /// </summary>
        internal static string ToolTipSettingsTaskDependency_Prefix_TaskDependencyType {
            get {
                return ResourceManager.GetString("ToolTipSettingsTaskDependency_Prefix_TaskDependencyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wird ausgelöst, nachdem sich der aktive Vorgang geändert hat. ähnelt.
        /// </summary>
        internal static string UltraGanttView_ActiveTaskChanged {
            get {
                return ResourceManager.GetString("UltraGanttView_ActiveTaskChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wird ausgelöst, bevor sich der aktive Vorgang ändert. ähnelt.
        /// </summary>
        internal static string UltraGanttView_ActiveTaskChanging {
            get {
                return ResourceManager.GetString("UltraGanttView_ActiveTaskChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wird ausgelöst, nachdemeine Zelle im Grid aktiviert wurde ähnelt.
        /// </summary>
        internal static string UltraGanttView_CellActivated {
            get {
                return ResourceManager.GetString("UltraGanttView_CellActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wird ausgelöst, bevor eine Zelle im Grid aktiviert wird ähnelt.
        /// </summary>
        internal static string UltraGanttView_CellActivating {
            get {
                return ResourceManager.GetString("UltraGanttView_CellActivating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wird ausgelöst, bevor eine Zelle im Grid deaktiviert wird ähnelt.
        /// </summary>
        internal static string UltraGanttView_CellDeactivating {
            get {
                return ResourceManager.GetString("UltraGanttView_CellDeactivating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows Forms-Steuerelement, welches einen Zeitplan zusammen mit seinen Vorgängen in einem Grid auf der einen Seite und eine Zeitleiste auf der anderen Seite präsentiert. ähnelt.
        /// </summary>
        internal static string UltraGanttView_Description {
            get {
                return ResourceManager.GetString("UltraGanttView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Vorgangs-Dialog kann nicht angezeigt werden, da der Vorgang und dieses Control nicht derselben Kalender zugeordnet sind. ähnelt.
        /// </summary>
        internal static string UltraGanttView_DisplayTaskDialog_Exception_CalendarInfoNotAssociated {
            get {
                return ResourceManager.GetString("UltraGanttView_DisplayTaskDialog_Exception_CalendarInfoNotAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; gehört zu einem anderen Projekt als das, das derzeit vom Steuerelement angezeigt wird, und kann nicht als ActiveTask bezeichnet werden. ähnelt.
        /// </summary>
        internal static string UltraGanttView_Exception_ActiveTaskNotAssociated {
            get {
                return ResourceManager.GetString("UltraGanttView_Exception_ActiveTaskNotAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Projekt kann dem Balkenplan nicht zugewiesen werden, da es nicht mit derselben Kalender-Instanz verknüpft ist. ähnelt.
        /// </summary>
        internal static string UltraGanttView_Exception_CannotAssignUnassociatedProject {
            get {
                return ResourceManager.GetString("UltraGanttView_Exception_CannotAssignUnassociatedProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wird ausgelöst, nachdem der Benutzer einen Vorgang hinzufügt hat. ähnelt.
        /// </summary>
        internal static string UltraGanttView_TaskAdded {
            get {
                return ResourceManager.GetString("UltraGanttView_TaskAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wird ausgelöst, bevor der Benutzer einen Vorgang hinzufügt. ähnelt.
        /// </summary>
        internal static string UltraGanttView_TaskAdding {
            get {
                return ResourceManager.GetString("UltraGanttView_TaskAdding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wird ausgelöst, nachdem der Benutzer einen Vorgang gelöscht hat. ähnelt.
        /// </summary>
        internal static string UltraGanttView_TaskDeleted {
            get {
                return ResourceManager.GetString("UltraGanttView_TaskDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wird ausgelöst, bevor der Benutzer einen Vorgang löscht. ähnelt.
        /// </summary>
        internal static string UltraGanttView_TaskDeleting {
            get {
                return ResourceManager.GetString("UltraGanttView_TaskDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wird ausgelöst, bevor der Dialog zum Vorgang angezeigt wird. ähnelt.
        /// </summary>
        internal static string UltraGanttView_TaskDialogDisplaying {
            get {
                return ResourceManager.GetString("UltraGanttView_TaskDialogDisplaying", resourceCulture);
            }
        }
    }
}
